/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:81ebfdf0-c24b-4608-baa6-dbf1f4a490ef",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_drfOt33q9",
    "aws_user_pools_web_client_id": "2j78enmdda74sh30cpvae73to9",
    "oauth": {
        "domain": "orbit-fitness-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1/,orbitFitnessClient://,exp://192.168.0.104/,orbitfitnessuserapp://",
        "redirectSignOut": "exp://127.0.0.1/,orbitFitnessClient://,orbitfitnessuserapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://h2ah3p5vevd4jpm7fvmt4qgepi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "orbitfitness170950-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
