export const APP_NAME_SIZE = 22

export const TITLE_IOS = 20; //bold
export const NAV_LINK_IOS = 17; //regular
export const PAGE_TITLE_IOS = 34; //bold
export const PAGE_TITLE_CENTERED_IOS = 17; //semibold
export const ITEM_TITLE_IOS = 17; //semibold
export const ITEM_DESC_IOS = 15; //regular
export const LIST_ITEM_IOS = 17; //regular
export const CAPTION_IOS = 13; //regular
export const BUTTON_IOS = 17; //semibold
export const SEGMENTED_BUTTON_IOS = 13; //regular
export const TEXT_INPUT_IOS = 17; //regular
export const SEARCH_BAR_IOS = 17; //regular
export const MODAL_TITLE_IOS = 17; //semibold
export const MODAL_DESC_IOS = 13; //regular
export const MODAL_TEXT_INPUT_IOS = 13; //regular
export const MODAL_DEFAULT_ACTION_IOS = 17; //semibold
export const MODAL_ACTION_IOS = 17; //regular

export const TITLE_ANDROID = 24; //bold
export const TEXT_INPUT_ANDROID = 16; //regular
export const PAGE_TITLE_ANDROID = 20; //semibold
export const BODY_ANDROID = 14; //regular
export const BUTTON_ANDROID = 16; //semibold
export const MODAL_BODY_ANDROID = 16; //regular
export const LIST_ITEM_ANDROID = 16; //regular  - for title use semibold
export const MENU_TITLE_ANDROID = 14; //semibold
export const ERROR_TEXT_ANDROID = 12; //semibold
export const CAPTION_ANDROID = 12; //regular
